# -------------------------------
# General
# -------------------------------
baseURL = 'https://mpapadopoullos.github.io'
locale = 'en-us'
title = 'mpx.http'
theme = 'archie'

# -------------------------------
# Code Highlight
# -------------------------------
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# -------------------------------
# Social
# -------------------------------

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/mpapadopoullos"

[[params.social]]
name = "Twitter"
icon = "twitter"

[[params.social]]
name = "GitLab"
icon = "gitlab"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/mpapadopoullos/"


# -------------------------------
# Sections
# -------------------------------
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 3
